name:                better-sentry-raven
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/better-sentry-raven#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - http-client
  - http-client-tls
  - http-types
  - aeson
  - aeson-casing
  - string-conv
  - time
  - hostname
  - exceptions
  - uuid
  - monad-logger
  - uri-bytestring
  - microlens
  - safe
  - containers
  - microlens-aeson
  - case-insensitive
  - microlens-th
  - microlens-aeson
  - monad-logger
  - fast-logger
  - wai
  - unliftio
  - random
  - mtl

ghc-options:
  - -Wall 
  - -fno-warn-orphans 
  - -fno-warn-unused-imports 
  - -fno-warn-dodgy-exports 
  - -Werror=missing-fields
  - -Werror=incomplete-patterns

library:
  source-dirs: src
  exposed-modules:
    - Sentry.Types
    - Sentry.Lens
    - Sentry.Blank
    - Sentry.HTTP
    - Sentry.MonadLogger
    - Sentry.SentryT

tests:
  test:
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    main: Test
    source-dirs:
      - src
      - test
    dependencies:
      - hedgehog
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-hedgehog
      - random
      - unliftio
      - hedgehog-gen
      - retry
